defaults:
  username: Kajih
  user_name: Kajih
  author_name: Kajih
  author_username: Kajih

  user_email: itskajih@gmail.com
  author_email: itskajih@gmail.com

  fullname: Julian Paquerot
  user_fullname: Julian Paquerot
  author_fullname: Julian Paquerot
  copyright_holder: Julian Paquerot

  repo_namespace: Kajiih
  github_username: Kajiih

  bluesky_url: https://bsky.app/profile/kajih.bsky.social
  linkedin_url: https://www.linkedin.com/in/kajih/
  youtube_url: ""
  discord_url: ""
  x_twitter_url: ""
  instagram_url: ""
  facebook_url: ""

trust:
  - https://github.com/Kajiih
