brew "mas"

# === Fonts ===
cask "font-fira-code-nerd-font"
cask "font-inter"


# === Terminal ===
cask "ghostty"
brew "nushell"
brew "uutils-coreutils"
brew "eza"
brew "git-delta"
brew "fzf"  
brew "fd"
brew "bat"
brew "atuin"
brew "tealdeer"
brew "thefuck"
brew "zoxide"
brew "ripgrep"
brew "yazi"
brew "starship"
brew "zellij"
brew "carapace"
brew "yazi"
brew "hyperfine"
brew "bandwhich"
brew "bottom"
brew "onefetch"

# --- Tools ---
brew "git"
brew "gh"
brew "grex"
brew "tesseract"
brew  "imageoptim-cli"
cask "imageoptim"
brew "pandoc"
brew "pre-commit"

# --- Python ---
brew "python"
brew "uv"
brew "ruff"

# === Apps ===
tap "nikitabobko/tap"
cask "aerospace"
tap "FelixKratz/formulae"
brew "borders"

cask "raycast"
cask "visual-studio-code"
cask "bitwarden"

# === Browser ===
cask "firefox"
tap "egovelox/mozeidon"
cask "mozeidon-macos-ui"

# === Testing ===
cask "docker"
brew "act"
