[data]
deviceName = "mystra.c.googlers.com"
deviceUsage = "professional"
useAndroidAutomotiveTools = true
isGoogleSpecific = true

    # This [data.chezmoi] table overrides the auto-detected values
    [data.chezmoi]
    os = "linux"
    osRelease.id = "debian"
